package py.gov.senatics.ws.prueba;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-11-30T09:32:15.366-03:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://identificaciones.ws.sii.senatics.gov.py/", name = "PersonaWS")
@XmlSeeAlso({ObjectFactory.class})
public interface PersonaWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findPersonaByCedula", targetNamespace = "http://identificaciones.ws.sii.senatics.gov.py/", className = "py.gov.senatics.ws.prueba.FindPersonaByCedula")
    @WebMethod
    @ResponseWrapper(localName = "findPersonaByCedulaResponse", targetNamespace = "http://identificaciones.ws.sii.senatics.gov.py/", className = "py.gov.senatics.ws.prueba.FindPersonaByCedulaResponse")
    public py.gov.senatics.ws.prueba.Persona findPersonaByCedula(
        @WebParam(name = "nroCedula", targetNamespace = "")
        java.lang.String nroCedula
    ) throws ServiceException_Exception, RegistroIdentificacionesException_Exception;
}
